src/Entity/MediaObject.php
<?php

namespace App\Entity;

use App\Repository\MediaObjectRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

#[ORM\Entity(repositoryClass: MediaObjectRepository::class)]
#[ORM\HasLifecycleCallbacks]
class MediaObject extends AbstractEntity
{
    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $path = null;

    #[ORM\Column(length: 255)]
    private ?string $extension = null;

    private ?UploadedFile $file = null;

    public function getFilePath(): string
    {
        $pathExploded = explode('public', $this->getPath());
        return sprintf('%s/%s', end($pathExploded), $this->getName());
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function setPath(string $path): static
    {
        $this->path = $path;

        return $this;
    }

    public function getExtension(): ?string
    {
        return $this->extension;
    }

    public function setExtension(string $extension): static
    {
        $this->extension = $extension;

        return $this;
    }

    public function getFile(): ?UploadedFile
    {
        return $this->file;
    }

    public function setFile(?UploadedFile $file): void
    {
        $this->file = $file;
    }
}

src/Form/Type/FigureType.php
<?php

namespace App\Form\Type;

use App\Entity\Figure;
use App\Entity\FigureGroup;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FigureType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        /** @var Figure $figure */
        $figure = $builder->getData();


        $builder
            ->add('title', TextType::class, [
                'label' => 'Titre',
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Description',
            ])
            ->add('figureGroup', EntityType::class, [
                'class' => FigureGroup::class,
                'choice_label'=> 'name',
                'label' => 'Groupe',
                'required' => false
            ])
            ->add('cover', FileType::class, [
                'label' => 'Image de profil',
                'mapped' => false,
            ])
            ->add('pictures', CollectionType::class, [
                'entry_type' => MediaObjectType::class,
                'allow_add' => true,
                'by_reference' => false,
                'allow_delete' => true,
                'mapped' => false,
                'label' => false
            ])
            ->add('youtubeVideos', CollectionType::class, [
                'entry_type' => TextType::class,
                'allow_add' => true,
                'by_reference' => false,
                'allow_delete' => true,
                'label' => false,
                'delete_empty' => true,
            ])
            ->add('save', SubmitType::class, [
                'label' => 'Enregistrer'
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'attr' => [
                'novalidate' => 'novalidate',
            ],
            'data_class' => Figure::class,
            'currentPictures' => null,
        ]);
    }
}

src/Controller/FigureController.php
<?php

namespace App\Controller;

use App\Entity\Commentaire;
use App\Entity\Figure;
use App\Entity\MediaObject;
use App\Form\Type\CommentaireType;
use App\Form\Type\FigureType;
use App\Repository\CommentaireRepository;
use App\Repository\FigureRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class FigureController extends AbstractController
{
    public function __construct(private EntityManagerInterface $em, private readonly CommentaireRepository $commentaireRepository, private readonly FigureRepository $figureRepository)
    {
    }

    #[Route('/figure/nouveau',name: 'app_figure_new')]
    #[IsGranted('ROLE_USER')]
    public function newFigure(Request $request): Response
    {
        $figure = new Figure();

        $form = $this
            ->createForm(FigureType::class, $figure)
            ->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $mediaObjects = $form->get('pictures')->getData();

                /**
                 * @var MediaObject $mediaObject
                 */
                foreach ($mediaObjects as $mediaObject) {
                    if (null !== ( $mediaObject = $this->uploadFile($mediaObject->getFile(),'tricks'))){
                        $figure->addPicture($mediaObject);
                    }
                }

                $cover = $form->get('cover')->getData();
                if (null !== ( $mediaObject = $this->uploadFile($cover,'tricks'))){
                    $figure->setCover($mediaObject);
                }


                $this->em->persist($figure);
                $this->em->flush();

                $this->addFlash(
                    'success',
                    'La figure de snowboard a bien été créée'
                );

                return $this->redirectToRoute('app_home_index');

            } catch (\Exception $e){
                $this->addFlash(
                    'error',
                    'L\'enregistrement de la figure a échoué'
                );
            }

        }

        return $this->render('figure/create.html.twig', [
            'form' => $form->createView(),
            'figure' => $figure
        ]);
    }


    private function uploadFile(?UploadedFile $file, string $folderName): ?MediaObject
    {
        if (!$file instanceof UploadedFile) {
            return null;
        }

        $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
        $orignalExtension = $file->guessExtension();
        $newFilename = sprintf('%s-%s.%s', $originalFilename, uniqid(), $orignalExtension);
        $destinationPath = sprintf('%s%s', $this->getParameter('uploads_directory'), $folderName);
        $file->move(
            $destinationPath,
            $newFilename
        );

        return (new MediaObject())
            ->setName($newFilename)
            ->setPath($destinationPath)
            ->setExtension($orignalExtension);
    }

    #[Route('/figure/{id}/edit',name: 'app_figure_edit')]
    #[IsGranted('ROLE_USER')]
    public function editFigure(Figure $figure, Request $request): Response
    {
        $originalPictures = new ArrayCollection();

        // Create an ArrayCollection of the current MediaObject objects in the database
        foreach ($figure->getPictures() as $picture) {
            $originalPictures->add($picture);
        }


        $form = $this
            ->createForm(FigureType::class, $figure)
            ->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /*try {

                foreach ($originalPictures as $picture) {
                    if (false === $figure->getPictures()->contains($picture)) {
                        $figure->removePicture($picture);
                    }
                }

                $this->em->persist($figure);
                $this->em->flush();

                $this->addFlash(
                    'success',
                    'La figure de snowboard a été modifiée'
                );

                return $this->redirectToRoute('app_figure_show',['slug'=>$figure->getSlug()]);

            } catch (\Exception $e){
                $this->addFlash(
                    'error',
                    'La figure du snowboard n\'a pas été créée'
                );
            }*/
            try {
                $mediaObjects = $form->get('pictures')->getData();

                /**
                 * @var MediaObject $mediaObject
                 */
                foreach ($mediaObjects as $mediaObject) {
                    if (null !== ( $mediaObject = $this->uploadFile($mediaObject->getFile(),'tricks'))){
                        $figure->addPicture($mediaObject);
                    }
                }

                $cover = $form->get('cover')->getData();
                if (null !== ( $mediaObject = $this->uploadFile($cover,'tricks'))){
                    $figure->setCover($mediaObject);
                }

                /*$mediaObjects = $form->get('pictures')->getData();
               @var MediaObject $picture
                foreach ($mediaObjects as $picture) {
                    if (false === $figure->getPictures()->contains($picture)) {
                        $figure->removePicture($picture);
                    }
                }*/

                $this->em->persist($figure);
                $this->em->flush();

                $this->addFlash(
                    'success',
                    'La figure de snowboard a été modifiée'
                );

                return $this->redirectToRoute('app_figure_show', ['slug' => $figure->getSlug()]);

            } catch (\Exception $e) {
                $this->addFlash(
                    'error',
                    'La figure du snowboard n\'a pas été modifiée'
                );

                return $this->redirectToRoute('app_figure_edit');
            }
        }

        return $this->render('figure/edit.html.twig', [
            'form' => $form->createView(),
            'pictures' => $figure->getPictures(),
            'figure' => $figure
        ]);
    }

    #[Route('/figure/{id}/delete',name: 'app_figure_delete')]
    #[IsGranted('ROLE_USER')]
    public function delete(Figure $figure): Response
    {
        $this->em->remove($figure);
        $this->em->flush();

        $this->addFlash(
            'success',
            'La figure du snowboard a été supprimée'
        );

        return $this->redirectToRoute('app_home_index');
    }



    #[Route('/figure/{id}/delete-media/{idMedia}', name: 'app_remove_media_from_figure')]
    #[IsGranted('ROLE_USER')]
    public function deleteMediaObject(Figure $figure, string $idMedia): Response
    {
        $mediaObjectRepository = $this->em->getRepository(MediaObject::class);
        $mediaObject = $mediaObjectRepository->find($idMedia);
        $figure->removePicture($mediaObject);
        $this->em->flush();

        $this->addFlash(
            'success',
            'La figure du snowboard a été mise à jour avec succès'
        );

        return $this->redirectToRoute('app_home_index');
    }

    #[Route('/fetch-comments-by-trick', name: 'app_fetch_comments_by_trick', methods: ['POST'])]
    public function commentsPaginationAjax(Request $request): Response
    {
        $perPage = (int) $request->get('perPage', 1);
        $page = (int) $request->get('page', 1);
        $trickId = $request->get('trickId', 2);

        $collection = $this->getPaginatedComments(
            $trickId,
            $perPage,
            $page
        );

        return $this->render('/embed/comment.html.twig', [
            'collection' => $collection,
        ]);
    }

    private function getPaginatedComments(
        int $trickId,
        int $perPage = 9,
        int $currentPage = 1,
    ): array {
        $total = $this->commentaireRepository->findTotalComments($trickId);

        $lastPage = (int) ceil($total / $perPage);
        $page = $currentPage > $lastPage ? 1 : $currentPage;
        $items = $this->commentaireRepository->findPaginatedComments(
            $trickId,
            $perPage,
            ($page * $perPage) - $perPage
        );

        return [
            'items' => $items,
            'total' => $total,
            'page' => $page,
            'per_page' => $perPage,
            'last_page' => $lastPage,
        ];
    }


    #[Route('/fetch-tricks', name: 'app_fetch_tricks')]
    public function tricksPaginationAjax(Request $request): Response
    {
        $perPage = (int)$request->get('perPage', 1);
        $page = (int)$request->get('page', 1);

        $collection = $this->getPaginatedTricks(
            $perPage,
            $page
        );
        return $this->render('/embed/trick_miniature.html.twig', [
            'collection' => $collection,
        ]);
    }

    private function getPaginatedTricks(
        int $perPage = 9,
        int $currentPage = 1,
    ): array
    {
        $total = $this->figureRepository->findTotalTricks();

        $lastPage = (int)ceil($total / $perPage);
        $page = $currentPage > $lastPage ? 1 : $currentPage;
        $items = $this->figureRepository->findPaginatedTricks(
            $perPage,
            ($page * $perPage) - $perPage
        );

        return [
            'items' => $items,
            'total' => $total,
            'page' => $page,
            'per_page' => $perPage,
            'last_page' => $lastPage,
        ];
    }

    #[Route('/figure/{slug}', name: 'app_figure_show')]
    public function show(Figure $figure, Request $request): Response
    {

templates/figure/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Ajouter une nouvelle figure
{% endblock %}
{% block body_id %}trick-form{% endblock %}
{% block body %}

    <div class="container">
        {% block form_title %}
            <div class="text-center">
                <h1>Ajouter une nouvelle figure</h1>
            </div>
        {% endblock %}

        <div class="row">
            <div class="col-12 col-lg-6 offset-lg-3">
                {{ form_start(form) }}

                {{ form_row(form.title, {
                    label: 'Titre :'
                }) }} {# Titre #}
                {{ form_row(form.figureGroup) }} {# Groupe #}
                {{ form_row(form.description) }} {# Description #}


                {# Image principal de la figure #}
                {% block form_cover_edit %}
                {% endblock %}
                <div id="form-field-trick-cover" {% if figure.cover %}hidden{% endif %}>
                    {{ form_row(form.cover) }}
                </div>


                {# Images de la figure #}
                <label class="form-label">Gallerie photos</label>
                {% block form_pictures_edit %}{% endblock %}

                <ul class="trick-pictures"
                    data-index="{{ form.pictures|length > 0 ? form.pictures|last.vars.name + 1 : 0 }}"
                    data-prototype="{{ form_widget(form.pictures.vars.prototype)|e('html_attr') }}"
                >
                </ul>

                <button type="button" class="add_item_link btn btn-dark"
                        data-collection-holder-class="trick-pictures">Ajouter une image
                </button>
                {{ form_errors(form.pictures) }}
                <br>


                {# Vidéo Youtube de la figure #}

                <label class="form-label">Vidéos Youtube :</label>


                <ul class="trick-youtubeVideos"
                    data-index="{{ form.youtubeVideos|length > 0 ? form.youtubeVideos|last.vars.name + 1 : 0 }}"
                    data-prototype="{{ form_widget(form.youtubeVideos.vars.prototype)|e('html_attr') }}"
                >
                    {% for emailField in form.youtubeVideos %}
                        <li class="youtubeVideos_field">
                            {{ form_errors(emailField) }}
                            {{ form_widget(emailField) }}
                        </li>
                    {% endfor %}
                </ul>

                <button type="button" class="add_item_link btn btn-dark"
                        data-collection-holder-class="trick-youtubeVideos">Ajouter une URL youtube
                </button>


                {{ form_row(form.save) }}

                {{ form_end(form) }}
            </div>
        </div>
    </div>


{% endblock %}

templates/figure/edit.html.twig
{% extends 'figure/create.html.twig' %}


{% block title %}
    Modification d'une figure
{% endblock %}

{% block form_title %}
    <div class="text-center">
        <h1>Modification de la figure : {{ figure.title }}</h1>
    </div>
{% endblock %}

{% block form_cover_edit %}
    {% if figure.cover %}
        <div id="form-trick-cover">
            {{ form_label(form.cover) }}
            <ul>
                <li class="trick-image">
                    <img class="img-thumbnail" alt="{{ figure.cover.name }}" src="{{ figure.cover.filePath }}">
                    <div class="action-trick-image">
                        <a href="" class="deleteTrickCoverButton" data-bs-toggle="modal"
                           data-bs-target="#deleteTrickCoverModal">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                 stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                      d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"></path>
                            </svg>
                        </a>
                    </div>
                </li>
            </ul>
            {{ include('figure/_partials/delete-trick-cover-modal.html.twig') }}
        </div>
    {% endif %}

{% endblock %}

{% block form_pictures_edit %}
    <ul>
        {% if figure.pictures %}
            {% for mediaObject in figure.pictures %}
                <li class="trick-image">
                    <img class="img-thumbnail" alt="{{ mediaObject.name }}" src="{{ mediaObject.filePath }}">
                    <div class="action-trick-image">
                        <a href="#" class="deleteTrickImgButton" data-figure-id="{{ figure.id }}"
                           data-mediaobject-id="{{ mediaObject.id }}" data-bs-toggle="modal"
                           data-bs-target="#deleteTrickImageModal">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                                 stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                      d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"></path>
                            </svg>
                        </a>
                    </div>
                </li>
            {% endfor %}
        {% endif %}
    </ul>

    {{ include('figure/_partials/delete-trick-images-modal.html.twig') }}

{% endblock %}

templates/figure/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Ajouter une nouvelle figure
{% endblock %}

{% block body %}
<h1>Ajouter une nouvelle figure</h1>

{{ form_start(form) }}

    {{ form_row(form.title) }}
    {{ form_row(form.figureGroup) }}
    {{ form_row(form.description) }}

{{ form_end(form) }}


{% endblock %}

templates/figure/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ figure.title }}{% endblock %}

{% block body_id %}figure{% endblock %}

{% block body %}
    <div class="container">
        <div class="figure-top">
            <h1>{{ figure.title }}</h1>
            <img src="{{ figure.cover.filePath }}" alt="Image de la figure">
            {% if app.user %}
            <div class="figure-action">
                <a href="{{ path('app_figure_edit', {'id':figure.id}) }}"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"></path></svg></a>
                <a href="#" class="deleteButton" data-id="{{ figure.id }}" data-bs-toggle="modal" data-bs-target="#deleteModal"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"></path></svg></a>
            </div>
            {% endif %}
        </div>
        <div class="figure-content">
            <div class="media-lists">
                <ul class="trick-images row row-cols-lg-6 row-cols-md-3 row-cols-2">
                    {% for mediaObject in figure.pictures %}
                        <li>
                            <img class="img-thumbnail trick-image" alt="{{ mediaObject.name }}" src="{{ mediaObject.filePath }}">
                        </li>
                    {% endfor %}
                </ul>
                <ul class="trick-videos row row-cols-lg-6 row-cols-md-3 row-cols-2">
                    {% for youtubeVideo in figure.youtubeVideos %}
                        <li class="youtubeVideos">
                            <div class="picto-yt">
                                <a href="{{ youtubeVideo }}" target="_blank">
                                    <img alt="icon youtube" class="img-fluid"
                                         src="{{ asset('/uploads/img/icon-youtube.svg') }}">
                                </a>
                            </div>
                            <img class="img-thumbnail" alt="{{ youtubeVideo }}" src="{{ youtubeVideo|getThumbnail }}">
                        </li>
                    {% endfor %}
                </ul>
                <div class="row justify-content-center d-lg-none">
                    <button class="btn btn-dark w-auto">Voir les médias</button>
                </div>
            </div>
            <div class="description">
                {{ figure.description }}
            </div>
            <div class="content-bottom">
                <div class="figure-group"><span>Groupe :</span><span>{{ figure.figureGroup.name }}</span></div>
                <div class="figure-date"><span>Crée le :</span><span>{{ figure.createdAt|date('d/m/Y') }}</span></div>
                {% if figure.createdAt|date('d/m/Y') != figure.updatedAt|date('d/m/Y') %}
                    <div class="figure-date"><span>Modifié le :</span><span>{{ figure.updatedAt|date('d/m/Y') }}</span></div>
                {% endif %}
            </div>

            <div class="row">
                <div class="col-12 col-lg-6 offset-lg-3 comment-bloc">
                    <div class="comment-list" id="comment-list">

                        {% if app.user %}
                            <div class="comment-form">
                                {{ form_start(form) }}
                                {{ form_widget(form) }}
                                {{ form_end(form) }}
                            </div>
                        {% else %}
                            <div class="comment-disable">
                                <p>Connectez-vous pour commenter cet article.</p>
                                <a class="btn btn-dark" href="{{ path('app_login') }}">Se connecter</a>
                            </div>
                        {% endif %}

                        <div class="bloc-header">
                            <div class="title">
                                <h2>Commentaires</h2>
                                <div class="tag"></div>
                            </div>
                        </div>

                        <div
                                class="bloc-content"
                                data-per-page="4"
                                data-url="{{ path('app_fetch_comments_by_trick') }}"
                                data-trick-id="{{ figure.id }}"
                        >

                        </div>
                    </div>

                    <button class="btn btn-dark" id="load-more-comments">
                        <span class="spinner-border spinner-border-sm spinner" aria-hidden="true" hidden></span>
                        <span role="status">Plus de commentaires</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
    {% include('figure/_partials/delete-modal.html.twig') %}
{% endblock %}